# -*- coding: utf-8 -*-
"""Laboratorio1_103_Cantarell.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Biu4MOleTBmaCEuyku22BrB7Y90sj0eq
"""

print ("Hola Mundo")

"""# Creacion de Dataframe"""

#Crea  nueva seccion
# Se importa libreria pandas y se asigna alias pd
import pandas as pd
#Se declara variable data como matriz de datos
data = [
    [1, "Alice", 25, "México"],
    [2, "Bob", 30, "Paris"],
    [3, "Carol", 35, "Venezuela"],
]

df = pd.DataFrame(data, columns=["id", "Nombre", "Edad", "Residencia"])
print(df)

"""# Montaje de Drive"""

import pandas as pd

csv_file_path = "/content/sample_data/california_housing_train.csv"

df = pd.read_csv(csv_file_path)
df.describe(include='all').round(1)
#df['total_rooms'].value_counts().sot.index().polt.bar(figsize=(10,6))

#print(df)

"""# Conexion con Drive"""



from google.colab import drive
drive.mount('/content/drive')